import fetch from 'node-fetch';
import dotenv from 'dotenv';
dotenv.config();

export async function generatePosterImage(prompt) {
    const apiKey = process.env.POLLINATIONS_API_KEY;
    const seed = Math.floor(Math.random() * 1000000);

    // Use the exact prompt generated by the LLM classifier for accurate image generation
    const enhancedPrompt = prompt;
    const encodedPrompt = encodeURIComponent(enhancedPrompt);

    try {
        if (apiKey) {
            // ✅ Authenticated Pollinations API — priority access, no rate limits
            console.log("🎨 Generating image via Authenticated Pollinations API...");

            const res = await fetch('https://gen.pollinations.ai/v1/images/generations', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiKey}`
                },
                body: JSON.stringify({
                    prompt: enhancedPrompt,
                    model: 'flux',
                    width: 1024,
                    height: 1024,
                    seed,
                    nologo: true
                })
            });

            if (res.ok) {
                const data = await res.json();
                // Return direct image URL from authenticated response
                const imageUrl = data?.data?.[0]?.url || data?.url;
                if (imageUrl) {
                    console.log("✅ Authenticated image generated:", imageUrl);
                    return imageUrl;
                }
            }

            console.warn("⚠️  Authenticated API failed, falling back to free URL mode...");
        }

        // 🆓 Free Pollinations URL (no key needed — works directly in browser)
        console.log("🎨 Generating image via free Pollinations URL...");
        const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1024&height=1024&seed=${seed}&model=flux&nologo=true`;
        return imageUrl;

    } catch (err) {
        console.error("Image Gen Error:", err.message);
        // Final fallback
        const cleanPrompt = encodeURIComponent(prompt);
        return `https://image.pollinations.ai/prompt/${cleanPrompt}?width=1024&height=1024&model=flux`;
    }
}
